### ISSUE TITLE
Virhe viikon 4 ohjeessa

### ISSUE THREAD

**Issue by Vanamo** [Tsoha/tsoha.github.io#2]
Tämä kohta:

// Tämä ei toimi! :(
array_merge($errors, $validator_errors);
// Tämä toimii :)
$errors = array_merge($errors, $validator_errors);

Alemmalla tavalla en saanut toimimaan, se loi taulukon jonka sisällä oli taulukko. Ylemmällä tavalla sen sijaan toimi.

**Comment by qzuw** [comment]
Äkkiseltään katsoen php:n kyseisen funktion dokumentaatio tarjoaa systemaattisesti tuota jälkimmäistä vaihtoehtoa. Itse funktion kuvaus on hieman epäselvä, joten en osaa varmasti sanoa tuosta ensimmäisestä vaihtoehdosta kokeilematta.

Jos tuo jälkimmäinen tapa palauttaa taulukon jonka sisällä on (myös) taulukko, niin tyypillisesti sille on silloin annettu taulukko, jonka sisällä on taulukko, jonka sisällä on taulukko.
