### ISSUE TITLE
Kintin linkki vanhentunut

### ISSUE THREAD

**Issue by AventusM** [Tsoha/tsoha.github.io#4]
Vkon 3 kpl 2.2 linkki Kintin repoon 404. [Tämä näyttäisi olevan ajankohtaisempi](https://github.com/kint-php/kint)

**Comment by qzuw** [comment]
Näköjään tänne ei tullut linkkiä committiin. Päivitin tuon osoitteen osoittamaan github.io-sivulle josta dokumentaatiota löytää paremmin ja josta on linkki myös github-repoon.
